version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000 # User ID (adjust as needed)
      - PGID=1000 # Group ID (adjust as needed)
      - TZ=Asia/Kolkata # Timezone (adjust as needed)
      - WEBUI_PORT=8080 # Web UI port (optional, default is 8080)
    volumes:
      - /mnt/sda1/media-mounts/qbittorrent-config:/config # Path to store qBittorrent configuration
      - /mnt/sda1/media-mounts/media/downloads:/downloads # Path for torrent downloads
    ports:
      - 6881:6881 # qBittorrent client port
      - 6881:6881/udp # qBittorrent client UDP port
      - 8080:8080 # Web UI port
    restart: unless-stopped
    networks:
      - media-network

networks:
  media-network:
    external: true
